### ISSUE TITLE
Is this a single thread?

### ISSUE THREAD

**Issue by shtse8** [x25/coinhive-stratum-mining-proxy#1]
I have read the source code, it seems it is a single thread, without creating a new thread to manage new connection. How about if many web users are browsing my site, can this proxy handle it all?

**Comment by x25** [comment]
The proxy uses an event-driven networking framework. Yes, the proxy can handle multiple clients in parallel.

**Comment by shtse8** [comment]
I have tried this proxy, but it seems I cannot connect to my proxy via websocket. any ideas?

**Comment by x25** [comment]
Use `ws://` and please share the code you use.

**Comment by shtse8** [comment]
```
root@pool-1:~/coinhive-stratum-mining-proxy# python coinhive-stratum-mining-proxy.py  xdn-xmr.pool.minergate.com 45790
2017-09-29 17:35:26+0000 [-] Log opened.
2017-09-29 17:35:26+0000 [-] Site starting on 8892
2017-09-29 17:35:26+0000 [-] Starting factory <twisted.web.server.Site instance at 0x7fd2c36d3680>
```

**Comment by x25** [comment]
You are trying to connect to an insecure WebSocket endpoint from https page.
There is two solutions:
1. Implement TLS: secure WebSocket support in proxy 
https://github.com/crossbario/autobahn-python/tree/master/examples/twisted/websocket/echo_tls
2. Use your http server to forward https/secure websocket requests to the local proxy port
https://stackoverflow.com/questions/12102110/nginx-to-reverse-proxy-websockets-and-enable-ssl-wss

**Comment by shtse8** [comment]
I am done now. It's working now. But there is no hashrate from the pool. But I can see the proxy is working.
