### ISSUE TITLE
Websocket reconnect many times

### ISSUE THREAD

**Issue by vphelipe** [x25/coinhive-stratum-mining-proxy#10]
I have a problem. My reports in coinhive.com show more KH / s than in my current pool, analyzing I can see that the websocket connection is reconnecting all the time, different from the original one of the coinhive that generates a websocket and keeps communicating with it. My current reports show only half of the KH / s generating on the coinhive dashboard. I have already changed pool several times and this persists, even with a low difficulty and with good communication with the pool.

**Comment by QuantumLeaper** [comment]
Hey hey, I have the same problem. I've tried using my own pool, and a few public pools. Hashrate is down the drain compared to coinhive. I find the biggest issue to be the connection time to the websocket itself, it's not instant like coinhives is, I have 4 servers running the websocket proxy and none of which connect fast. Plus it also reconnects quite a bit, seems to be sporadic though.

**Comment by vphelipe** [comment]
What is the configuration of your servers? I'm with 1500 miners connected to my pool at the moment, what best communicates with this script is minergate.com. It has very fast response, but the speed reports are inconsistent. What is the best public pool you have found?

**Comment by QuantumLeaper** [comment]
Hey! I found that running the python version rather than docker seemed to resolve my issues, getting wicked hashes now, actually even better than I was getting with CoinHive. Much thanks!!!

**Comment by x25** [comment]
@vphelipe try to use nginx as the load balancer and the ssl termination point
+ try to update the twisted to the latest version
+ take a look at pypy / cpython

**Comment by vphelipe** [comment]
The problem was solved in part. Using the xmr-eu1.nanopool.org pool the reconnections have stopped, but the hashrate continues below of expected. I switched to a server with triple of processing and memory compared to the old server and even then I could not raise the hashrate. :(
