### ISSUE TITLE
README Unclear

### ISSUE THREAD

**Issue by Emiller88** [x25/coinhive-stratum-mining-proxy#13]
Is this a viable alternative to CoinHive on a site, or is this just so I can mine from a browser using their Javascript Miner?

**Comment by vphelipe** [comment]
Hello, this script does the same service as coinhive.com, but mine directly to your pool, you need to run this script in you server to your visitors connect. So you do not pay 30% to coinhive, that's just great.

**Comment by Emiller88** [comment]
Sweet. Would it work using github pages?

**Comment by vphelipe** [comment]
No, this site only shares the source code, you must have a server to run this script.

**Comment by Emiller88** [comment]
I meant I am hosting on Github Pages, so if I add this code to my site's repo will it work? Or do I need to host it on a separate server for it to be accessed?

**Comment by x25** [comment]
you need a server with a python environment

**Comment by Emiller88** [comment]
So if I had a server with python, I could connect the user miners from my site through the proxy to an actual exchange?

**Comment by x25** [comment]
@Emiller88 yes, the proxy will connect the web of miners and the pool

**Comment by Emiller88** [comment]
Sounds good. We're having an issue with setting up web sockets properly because they're not secure. Any advice? Feel free to shoot me an email also

**Comment by x25** [comment]
@Emiller88  see https://github.com/x25/coinhive-stratum-mining-proxy/issues/4
