### ISSUE TITLE
Miner Script is detected as JS:Miner-C by Avast AntiVirus

### ISSUE THREAD

**Issue by denniske** [x25/coinhive-stratum-mining-proxy#18]
Hi

I just checked out the project and the Miner Script miner.min.js is detected as JS:Miner-C by Avast AntiVirus.

Is there anything I can do about it?

![avast](https://user-images.githubusercontent.com/1076211/31310984-fa33deca-aba2-11e7-9025-0fac0627f06f.png)

**Comment by vphelipe** [comment]
Try use js obfuscator.

**Comment by denniske** [comment]
Okay will do. Thx.
