### ISSUE TITLE
Server disconnected: Connection was closed cleanly.

### ISSUE THREAD

**Issue by denniske** [x25/coinhive-stratum-mining-proxy#19]
I am seeing this a lot in my logs when running the proxy:

> 11:12:40+0000 [HTTPChannel,1001,<ip>] Client disconnected (True, 1001, None)
> 11:12:40+0000 [HTTPChannel,1001,<ip>] Client disconnecting from server
> 11:12:40+0000 [ProxyClient,client] Server disconnected ([Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionDone'>: Connection was closed cleanly.])
> 11:12:40+0000 [ProxyClient,client] Server disconnecting from client
> 11:12:40+0000 [-] Stopping factory <__main__.ProxyClientFactory instance at 0x7f33977b4dd0>

Can you confirm that this is normal behaviour and happens when a user navigates away from the page /static/index.html?

**Comment by vphelipe** [comment]
By my tests this error is always generated that the visitor leaves the page.

**Comment by denniske** [comment]
I will do that. Thx!
