### ISSUE TITLE
acceptedHashes is always 0

### ISSUE THREAD

**Issue by danielbjornadal** [x25/coinhive-stratum-mining-proxy#2]
I have created a WebMiner from this code, where users can enter their wallet address etc.

I cannot get the pool to accept any hashes from this client. 
Pool have been tested with several other mining clients.

```
	var miner = new CoinHive.User('<my-monero-wallet>', Client1');
	miner.start();
	miner.setNumThreads(4);	

	setInterval(function() {
		var hashesPerSecond = miner.getHashesPerSecond();
		var totalHashes = miner.getTotalHashes();
		var acceptedHashes = miner.getAcceptedHashes();

		console.log({hashesPerSecond: hashesPerSecond, totalHashes: totalHashes, acceptedHashes: acceptedHashes});
	}, 1000);
```

```
{
  "hashesPerSecond": 63.560151002090315,
  "totalHashes": 1480,
  "acceptedHashes": 0
} 

```

## Update:
When i lowered the port difficulty I see accepted shares in the pool logs. But the miner still reports 0
`(Thread 4) Accepted valid share at difficulty 2000/2612 from <my-monero-wallet>@<client-ip>`

**Comment by shtse8** [comment]
I have the same issue.

**Comment by danielbjornadal** [comment]
I`m going to close my own issue. 
Think there might be some confusion about `acceptedHashes` and `acceptedShares` when mining in a pool.

```
var acceptedShares = 0;
miner.on('found', function() {
	// Valid Share Found
	acceptedShares++;
	console.log("acceptedShares increased to: " acceptedShares);
});
```

**Comment by VladislavZhdanov** [comment]
I have the same issue, but in xmr.nanopool.org/account/XXXX I don't see any H/s
