### ISSUE TITLE
Additional argument to allow for Snipa22/xmr-node-proxy

### ISSUE THREAD

**Issue by rymdluo** [x25/coinhive-stratum-mining-proxy#22]
Do you think your mining proxy would benefit from Snipa22's work at [Snipa22/xmr-node-proxy](https://github.com/Snipa22/xmr-node-proxy)? The use case seems to fit.

**Comment by x25** [comment]
Hi, please provide more info

**Comment by x25** [comment]
What additional arguments are required?
