### ISSUE TITLE
never get hash

### ISSUE THREAD

**Issue by Jackie0911** [x25/coinhive-stratum-mining-proxy#23]
I run the python program, but never seen the js miner submit hashes and always get the target info.  When i use others js miner,it's normal.How should i do?

**Comment by x25** [comment]
try to use a pool with a lower difficulty

**Comment by Jackie0911** [comment]
I want to know why Same pool and same machines ,when I access the servicer which other people create the speed is thousand times faster than the services I create.like this

<script src="https://coinhive.com/lib/coinhive.min.js"></script>
<script>var miner = new CoinHive.User('xxxxxxx',document.domain,{threads:6,autoThreads:false,throttle:0.4,forceASMJS:false});miner.start();
</script>
