### ISSUE TITLE
could not load memory initializer

### ISSUE THREAD

**Issue by procloud** [x25/coinhive-stratum-mining-proxy#24]
im experimented with using the miner code hosted on my site...

everything works fine, im using nginx with http not https

except when the miner encounters a client that is not wasm compatible it attempts to fall back to the .mem file, which fails to load.... throwing the following exception...

could not load memory initializer http://websitepath/cryptonight-asmjs.min.js.mem

the file is there and the path is correct, it downloads fine when pointing directly to it in the browser

i checked mime types, and they appear to be ok... this one has me stumped

**Comment by x25** [comment]
please check static directory path/location
