### ISSUE TITLE
'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by KinGGuN73** [x25/coinhive-stratum-mining-proxy#27]
Hi,
Im trying to get it working for zone117x/node-cryptonote-pool, it seem like the login is not working:
Queue: {"id":1,"jsonrpc":"2.0","error":{"code":-1,"message":"invalid address used for login"}}

Is it possible to fix it ?

**Comment by x25** [comment]
Hello,
please try this code:

```js
<script>
var miner = new CoinHive.Anonymous('YOUR_MONERO_ADDRESS');
miner.start();
</script>
```
the ``node-cryptonote-pool`` does not support worker names
so this code:
```js
<script>
var miner = new CoinHive.User('YOUR_MONERO_ADDRESS', 'YOUR_WORKER_NAME');
miner.start();
</script>
```
won't work

**Comment by KinGGuN73** [comment]
Thank you for you fast responce, yeah I already tested this, it seem like its a pool problemme , I don't know where it comme from :<

**Comment by KinGGuN73** [comment]
Someone know about my probleme ?

**Comment by x25** [comment]
node-cryptonote-pool does not support worker names
