### ISSUE TITLE
Try to git clone with error permission denied

### ISSUE THREAD

**Issue by ChristianGrieger** [x25/coinhive-stratum-mining-proxy#3]
$ git clone git@github.com:x25/coinhive-stratum-mining-proxy.git
Cloning into 'coinhive-stratum-mining-proxy'...
Warning: Permanently added the RSA host key for IP address '192.30.253.112' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by x25** [comment]
Hello, please try:
```
$ git clone https://github.com/x25/coinhive-stratum-mining-proxy.git
```

**Comment by ChristianGrieger** [comment]
worked well thank you now try to get it running. Installed on debian vps but hash seems not to work yet.

**Comment by x25** [comment]
You are trying to connect to an insecure WebSocket endpoint from https page.
There is two solutions:

1. Implement TLS: secure WebSocket support in proxy 
https://github.com/crossbario/autobahn-python/tree/master/examples/twisted/websocket/echo_tls
2. Use your http server to forward https/secure websocket requests to the local proxy port
https://stackoverflow.com/questions/12102110/nginx-to-reverse-proxy-websockets-and-enable-ssl-wss

**Comment by ChristianGrieger** [comment]
I am not able to add this on my own :/ the miner and the server where the stratum is installed are different servers. So i need to give up at this point.

**Comment by ChristianGrieger** [comment]
i dont know why but it runs now... thanks for your help
