### ISSUE TITLE
Connect to pool via SSL as well

### ISSUE THREAD

**Issue by chron0** [x25/coinhive-stratum-mining-proxy#31]
I have been playing with CSMP a bit and it's working great, thanks for sharing. But I can't seem to connect to a pool via SSL. It would be great to have all communication secured, not only via websocket but proxy <-> pool as well. I've started digging through the code but I haven't found where that would be implemented yet. Any hints?

**Comment by aleqx** [comment]
Use stunnel pointed at 127.0.0.1 as a temporary workaround (it might in fact be faster than the native ssl implementation in JS)
