### ISSUE TITLE
Problem with multiple connections

### ISSUE THREAD

**Issue by vphelipe** [x25/coinhive-stratum-mining-proxy#32]
I'm having difficulty maintaining more than 20,000 simultaneous connections. After this number, the script does not respond to new connections.

There is a perl script for mining ZEC that supports multiple connections:
https://github.com/mtve/yazecminer

Is there any configuration to make it work?

**Comment by x25** [comment]
duplicate https://github.com/x25/coinhive-stratum-mining-proxy/issues/38
