### ISSUE TITLE
open different port failure

### ISSUE THREAD

**Issue by vsystech** [x25/coinhive-stratum-mining-proxy#34]
Hello, i'm start open proxy on different port and have a problem. 

i'm upload a thumb ! 

http://prntscr.com/hi9mqk

**Comment by x25** [comment]
run with ``--websocket_port=8092`` argument

**Comment by vsystech** [comment]
Thanks, other question how can i run 

docker run -p 8892:8892 coinhive-stratum-mining-proxy pool.supportxmr.com 3333

in background ? 

and i'm change the miner/miner.min.js localhost to my ip address. but when load from browser 8892/miner/miner.min.js, not changed. i'm try restart the computer and start again the proxy but not make the changes. (Yes, try CTRL + F5 ) ) 

Thanks your help!

**Comment by x25** [comment]
Replace "localhost:8892" to "yourhost" in ./miner/miner.min.js and in ./miner/cryptonight-asmjs.min.js 

``$ sed -i 's/localhost:8892/yourhost.com/g' ./miner/miner.min.js``
``$ sed -i 's/localhost:8892/yourhost.com/g' ./miner/cryptonight-asmjs.min.js``
