### ISSUE TITLE
SSL Problem

### ISSUE THREAD

**Issue by vsystech** [x25/coinhive-stratum-mining-proxy#35]
Hello, i have a problem with ssl function. 

root@:~/coinhive-stratum-mining-proxy# docker run -p 8892:8892 coinhive-stratum-mining-proxy pool.supportxmr.com 3333 --ssl=key.pem:cert.pem
2017-12-07 11:12:39+0000 [-] Log opened.
2017-12-07 11:12:39+0000 [-] Invalid privatekey:certificate pair

**Comment by vsystech** [comment]
i'm try open javascript miner from ssl based website but error: 

was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://...............:8892/proxy'. This request has been blocked; this endpoint must be available over WSS.

**Comment by vsystech** [comment]
I'm try with openssl req -x509 -newkey rsa:2048 -keyout key.pem -out cert.pem -days 100 -nodes

and try cloudflare ssl . but not working. some error. 

maybe can you help me ?

**Comment by vphelipe** [comment]
Hey, you need change ws:// to wss://

:)

**Comment by vsystech** [comment]
Dear vphelipe, you not read my problem. i'm try start the server but exit. 

root@:~/coinhive-stratum-mining-proxy# docker run -p 8892:8892 coinhive-stratum-mining-proxy pool.supportxmr.com 3333 --ssl=key.pem:cert.pem
2017-12-07 11:12:39+0000 [-] Log opened.
2017-12-07 11:12:39+0000 [-] Invalid privatekey:certificate pair

and stop the process..

**Comment by x25** [comment]
docker does not see the host machine files in your case
try python version
