### ISSUE TITLE
accepted 0 

### ISSUE THREAD

**Issue by svirusxxx** [x25/coinhive-stratum-mining-proxy#36]
Hi
I just try to run it.
ButI see about 30H/s Total Hashes is increasing, but acceted hashes is 0
I make my own pool, and set diff to "10" ... about few minutes there is no any share.
It's realy works ?

I also try it on others pool , and have samae result.
My pool is working in 100% , cpu miners and gpu miners sending many shares.

**Comment by vphelipe** [comment]
Try:


var acceptedShares = 0;
	miner.on('found', function() {
		acceptedShares++;
		console.log("AcpShares = " + acceptedShares);
	});

**Comment by svirusxxx** [comment]
very strange, I found the problem and solution
I changed line 159 and I removed the dot and user
it's strange, but my pool when see wrong username, then send strange job:
`
**{"id":1,"jsonrpc":"2.0","error":null,"result":{"id":"414398031076416","job":{"blob":"0606f38da6d105a19831e98ccaf729a20e944cd07840da61ba365fd2cf073091ee1fc2e42dd5cb00000000054b11b58b4da8b7c74f9215f162fcb3ed6e9708863c433a3fa2a64c8713fbfb0d","job_id":"154414491658098","target":"00000000"},"status":"OK"}**
`
target 0000 ;)
