### ISSUE TITLE
No dev fee

### ISSUE THREAD

**Issue by nbhat000** [x25/coinhive-stratum-mining-proxy#37]
When you say "no dev fee", does this mean that this bypasses CoinHive's 30% cut of whatever you mine using their service? As in, the funds can be mined through a completely separate mining pool that has no affiliation with CoinHive, so whatever you mine is completely owned by you? Or does this still route the mining earnings through CoinHive first, and then to the mining pool? Thanks in advance!

**Comment by BlankTBR** [comment]
please see https://github.com/x25/coinhive-stratum-mining-proxy/issues/25

**Comment by nbhat000** [comment]
Thank you!
