### ISSUE TITLE
SSL (wss://) support for HTTPS pages

### ISSUE THREAD

**Issue by x25** [x25/coinhive-stratum-mining-proxy#4]
There is an error on the https pages in the browser:

```
Mixed Content: The page at 'xxxxxxxxxxx' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://poolhost:8892/proxy'. This request has been blocked; this endpoint must be available over WSS.
```
There is two solutions:

1. Implement TLS: secure WebSocket bindings in proxy
https://github.com/crossbario/autobahn-python/tree/master/examples/twisted/websocket/echo_tls

```python
contextFactory = ssl.DefaultOpenSSLContextFactory('server.key', 'server.crt')
autobahn.twisted.websocket.listenWS(ws, contextFactory)
twisted.internet.reactor.listenSSL(8892, site, contextFactory)
```

2. Use reverse proxy to forward `wss://` requests to the local proxy port
https://stackoverflow.com/questions/12102110/nginx-to-reverse-proxy-websockets-and-enable-ssl-wss

Sample nginx configuration:

```nginx
location /proxy {
    proxy_pass ​http://localhost:8892;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_read_timeout 86400;
}
```

**Comment by vphelipe** [comment]
My solution, change to your key and crt:

    root = Root('./static')
    root.putChild(b"proxy", autobahn.twisted.resource.WebSocketResource(ws))
    site = twisted.web.server.Site(root)
    twisted.internet.reactor.listenSSL(9992,site,ssl.DefaultOpenSSLContextFactory('ctr_key/x.key', 'ctr_key/x.crt'))   
    twisted.internet.reactor.run()

**Comment by kiezpr0grammer** [comment]
@vphelipe 

when i use your solution i'l# get the following error:
File "/coinhive-stratum-mining-proxy.py", line 39, in <module>
    from twisted.internet import ssl
  File "/usr/lib/python2.7/site-packages/twisted/internet/ssl.py", line 59, in <module>
    from OpenSSL import SSL
ImportError: No module named OpenSSL

How can i solve this error?

**Comment by vphelipe** [comment]
@kiezpr0grammer hello! Solution:
apt-get install python-openssl

**Comment by kiezpr0grammer** [comment]
@vphelipe i already have installed it, but still no success -.-

> python-openssl is already the newest version (16.2.0-1).
0 upgraded, 0 newly installed, 0 to remove and 79 not upgraded.

**Comment by vphelipe** [comment]
@kiezpr0grammer ok, try: pip install pyOpenSSL

**Comment by kiezpr0grammer** [comment]
@vphelipe sorry, to bother you, but i'm new to that whole docker python thing

where do i have to put it in the dockerfile? would be 

> # Install dependencies
RUN apk add --no-cache python python-dev openssl-dev gcc musl-dev git && \
    python -m ensurepip && \
    rm -r /usr/lib/python*/ensurepip && \
    pip install --upgrade pip setuptools pip install pyOpenSSL && \
    rm -r /root/.cache


correct?

**Comment by kiezpr0grammer** [comment]
okay, i mangend to install it, but the build process exits with an error :(

> Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-DzQvvg/cffi/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-xTrgvg-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-DzQvvg/cffi/

**Comment by vphelipe** [comment]
Sorry but I do not use docker :(

**Comment by kiezpr0grammer** [comment]
@vphelipe thanks for your help, i just used the python way and not the dockerway and it works like a charm 👯‍♂️

**Comment by x25** [comment]
SSL support is implemented! Thanks to @zatarra
