### ISSUE TITLE
Not Able to Use coinhive.min.js Locally

### ISSUE THREAD

**Issue by theabhinavdas** [x25/coinhive-stratum-mining-proxy#41]
Hey, I was mining using this setup but with the help of xmr-node-proxy by Snipa. Today, I'm unable to use the coinhive.min.js code even though I was hosting locally. I believe they changed something with the wasm that prevent non-coinhive users from using it. Do you have a workaround?

**Comment by x25** [comment]
Do you have any errors in logs? The proxy works good with nanopool without any changes.

**Comment by theabhinavdas** [comment]
Hey, yes! I get the following errors on Mozilla Firefox (Xubuntu 16.04) with AdBlock.

```
failed to asynchronously prepare wasm: TypeError: NetworkError when attempting to fetch resource.
52952ff1-7c9a-4098-af23-301f7e2a1de4:1:5096
TypeError: NetworkError when attempting to fetch resource.
52952ff1-7c9a-4098-af23-301f7e2a1de4:1:5011
TypeError: NetworkError when attempting to fetch resource.
```

**Comment by x25** [comment]
Try to rename and obfuscate js files to bypass adblock
